daemon off;
worker_processes 1;
pid run/nginx.pid;
error_log run/error.log;

events {
    worker_connections 64;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log run/access.log;
    client_body_temp_path run/client_body_temp;

    server {
        listen 8080;
        server_name localhost;
        root ../pages;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
